
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-10am-1
owner: ucsb-cs156-m23
repo_name: team03-m23-10am-1
pull_requests: [{"author":{"id":"U_kgDOBnGf2A","is_bot":false,"login":"marcushuang1","name":""},"headRefName":"Ziyang-Final","number":75,"title":"Ziyang final","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/75"},{"author":{"id":"U_kgDOBXjmyQ","is_bot":false,"login":"ZixiaoJin","name":""},"headRefName":"ZixiaoJin-AppAppNavbar","number":73,"title":"Zixiao jin app app navbar","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/73"},{"author":{"id":"U_kgDOBnGf2A","is_bot":false,"login":"marcushuang1","name":""},"headRefName":"Ziyang-OrganizationPages","number":72,"title":"Ziyang organization pages","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/72"},{"author":{"id":"MDQ6VXNlcjYzOTk0NTY2","is_bot":false,"login":"EthanSun210","name":""},"headRefName":"Ethan-menuItemReviewPages","number":70,"title":"es - Add MenuItemReviewTable and Page","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/70"},{"author":{"id":"MDQ6VXNlcjYzOTk0NTY2","is_bot":false,"login":"EthanSun210","name":""},"headRefName":"Ethan-menuItemReviewTable","number":65,"title":"es - Add menuItemReviewTable related files","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/65"}]
