
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-10am-1
owner: ucsb-cs156-m23
repo_name: team03-m23-10am-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjYzOTk0NTY2","is_bot":false,"login":"EthanSun210","name":""},"headRefName":"Ethan-menuItemReviewPages","number":69,"title":"es - Add menuItemReviewTable and Pages","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/69"},{"author":{"id":"U_kgDOBXjmyQ","is_bot":false,"login":"ZixiaoJin","name":""},"headRefName":"Zixiao-RecommendationRequest","number":68,"title":"local done","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/68"},{"author":{"id":"MDQ6VXNlcjYzOTk0NTY2","is_bot":false,"login":"EthanSun210","name":""},"headRefName":"Ethan-menuItemReviewTable","number":65,"title":"es - Add menuItemReviewTable related files","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/65"}]
