
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-10am-1
owner: ucsb-cs156-m23
repo_name: team03-m23-10am-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzMDI3NTY4","is_bot":false,"login":"haostevewu","name":"Hao Wu"},"headRefName":"Hao-FormComponent","number":58,"title":"Hao form component","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/58"},{"author":{"id":"MDQ6VXNlcjMzMDI3NTY4","is_bot":false,"login":"haostevewu","name":"Hao Wu"},"headRefName":"Hao-Copyteam02","number":56,"title":"Hao copyteam02","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/56"},{"author":{"id":"MDQ6VXNlcjMzMDI3NTY4","is_bot":false,"login":"haostevewu","name":"Hao Wu"},"headRefName":"Hao-ucsbMenuItemFixtures","number":55,"title":"hw - add menu item fixture","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/55"}]
