
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team03-m23-10am-1
owner: ucsb-cs156-m23
repo_name: team03-m23-10am-1
pull_requests: [{"author":{"id":"U_kgDOBXjmyQ","is_bot":false,"login":"ZixiaoJin","name":""},"headRefName":"ZixiaoJin-Table","number":82,"title":"table fixed","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/82"},{"author":{"id":"U_kgDOBXjmyQ","is_bot":false,"login":"ZixiaoJin","name":""},"headRefName":"ZixiaoJin-AppAppNavbar","number":73,"title":"Zixiao jin app app navbar","url":"https://github.com/ucsb-cs156-m23/team03-m23-10am-1/pull/73"}]
